#!/usr/bin/env python3
# This file is distributed under the BSD 3-Clause License. See LICENSE for details.
"""Generate prpparse/unicode_ident.hpp: the code-point ranges of the Unicode
letters (\\p{L}) and decimal digits (\\p{Nd}), the identifier characters of
grammar.js `identifier` (`[\\p{L}\\p{Nd}_]`).

    python3 prpparse/tools/gen_unicode_ident.py > prpparse/unicode_ident.hpp
"""
import sys
import unicodedata


def ranges(pred):
    out = []
    start = None
    for cp in range(0x110000):
        ok = pred(unicodedata.category(chr(cp)))
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print(f"inline constexpr Cp_range {name}[] = {{")
    line = "   "
    for a, b in rs:
        item = f" {{0x{a:X}, 0x{b:X}}},"
        if len(line) + len(item) > 118:
            print(line)
            line = "   "
        line += item
    print(line)
    print("};")


def main():
    print("// This file is distributed under the BSD 3-Clause License. See LICENSE for details.")
    print("// GENERATED by prpparse/tools/gen_unicode_ident.py (Unicode "
          f"{unicodedata.unidata_version}) -- do not edit.")
    print("#pragma once")
    print()
    print("#include <cstddef>")
    print("#include <cstdint>")
    print()
    print("namespace prpparse::unicode {")
    print()
    print("struct Cp_range {")
    print("  uint32_t lo;")
    print("  uint32_t hi;")
    print("};")
    print()
    print("// \\p{L}: every letter category (Lu, Ll, Lt, Lm, Lo).")
    emit("kLetters", ranges(lambda c: c.startswith("L")))
    print()
    print("// \\p{Nd}: decimal digits.")
    emit("kDigits", ranges(lambda c: c == "Nd"))
    print()
    print("template <size_t N>")
    print("constexpr bool in_ranges(const Cp_range (&rs)[N], uint32_t cp) {")
    print("  size_t lo = 0, hi = N;")
    print("  while (lo < hi) {")
    print("    size_t mid = (lo + hi) / 2;")
    print("    if (cp < rs[mid].lo) hi = mid;")
    print("    else if (cp > rs[mid].hi) lo = mid + 1;")
    print("    else return true;")
    print("  }")
    print("  return false;")
    print("}")
    print()
    print("constexpr bool is_letter(uint32_t cp) { return in_ranges(kLetters, cp); }")
    print("constexpr bool is_digit(uint32_t cp) { return in_ranges(kDigits, cp); }")
    print()
    print("}  // namespace prpparse::unicode")


if __name__ == "__main__":
    sys.exit(main())
