#!/usr/bin/env python3
# This file is distributed under the BSD 3-Clause License. See LICENSE for details.
#
# Generate prp_nodes.def (node kinds) and prp_fields.def (field roles) from the
# tree-sitter-pyrope src/node-types.json. The kind enum packs into the high 10
# bits and the field enum into the low 6 bits of hhds's per-node Type (uint16).
#
#   python3 prpparse/tools/gen_nodes.py
#
# Re-run after grammar.js changes the node/field vocabulary. The generated .def
# files are checked in (hand edits are discouraged; regenerate instead).

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))  # repo root
NODE_TYPES = os.path.join(ROOT, "src", "node-types.json")
OUT_DIR = os.path.dirname(HERE)  # prpparse/


def main():
    with open(NODE_TYPES) as f:
        data = json.load(f)

    kinds = set()
    fields = set()
    for entry in data:
        if entry.get("named") and "type" in entry:
            kinds.add(entry["type"])
        for fname in (entry.get("fields") or {}).keys():
            fields.add(fname)

    kinds = sorted(kinds)
    fields = sorted(fields)

    if len(kinds) > 1023:
        sys.exit(f"too many kinds ({len(kinds)}) to fit 10 bits")
    if len(fields) > 63:
        sys.exit(f"too many fields ({len(fields)}) to fit 6 bits")

    header = (
        "// GENERATED by prpparse/tools/gen_nodes.py from src/node-types.json.\n"
        "// Do not edit by hand; regenerate after grammar.js vocabulary changes.\n"
    )

    nodes_path = os.path.join(OUT_DIR, "prp_nodes.def")
    with open(nodes_path, "w") as f:
        f.write(header)
        f.write("// %d named node kinds (fit 10 bits).\n" % len(kinds))
        f.write("#ifndef PRP_NODE\n#error \"define PRP_NODE(name) before include\"\n#endif\n")
        for k in kinds:
            f.write("PRP_NODE(%s)\n" % k)
        f.write("#undef PRP_NODE\n")

    fields_path = os.path.join(OUT_DIR, "prp_fields.def")
    with open(fields_path, "w") as f:
        f.write(header)
        f.write("// %d field roles (fit 6 bits).\n" % len(fields))
        f.write("#ifndef PRP_FIELD\n#error \"define PRP_FIELD(name) before include\"\n#endif\n")
        for fl in fields:
            f.write("PRP_FIELD(%s)\n" % fl)
        f.write("#undef PRP_FIELD\n")

    print("wrote %s (%d kinds)" % (nodes_path, len(kinds)))
    print("wrote %s (%d fields)" % (fields_path, len(fields)))


if __name__ == "__main__":
    main()
